### ISSUE TITLE
请问字体DPI怎么填?

### ISSUE THREAD

**Issue by darwinstudio** [createskyblue/Easy-u8g2-font-generate-tools#1]
RT,我用的12864LCD屏幕

**Comment by createskyblue** [comment]
DPI： 96

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月2日 16:21
收件人: ***@***.***>
抄送: ***@***.***>
主题: [createskyblue/Easy-u8g2-font-generate-tools] 请问字体DPI怎么填? (Issue #1)


RT,我用的12864LCD屏幕

―
